# Generated by Django 4.0 on 2022-01-01 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('booking', '0002_alter_booking_doctor_alter_booking_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='doctor',
        ),
        migrations.AddField(
            model_name='room',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='purpose_of_booking',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
